import React, { useEffect } from 'react';
import { Provider } from 'react-redux';
import { SafeAreaView, StyleSheet } from 'react-native';
// Required to use random values generated by uuid library
import 'react-native-get-random-values';
import Purchases from 'react-native-purchases';

import Main from './Main';
import { store } from './data/store';

export default function App() {
  // Configure purchases once, on app first load
  Purchases.setDebugLogsEnabled(true);
  Purchases.setup('ZvbtbeGMyhvgaVdtIfEgqwokXGQBppba');

  return (
    <Provider store={store}>
      <SafeAreaView style={styles.container}>
        <Main />
      </SafeAreaView>
    </Provider>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
});
